runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: Guolewen1234
  CLOUD_SQL_DATABASE_NAME: personal
  CLOUD_SQL_CONNECTION_NAME: homepage-235203:asia-east2:homepage



handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images


  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
